/**
 * fetchCultures.ts
 * Client-side helpers for loading per-province culture data from static JSON files.
 * JSON files are generated by scripts/split-cultures.mjs and live in /public/data/cultures/.
 *
 * Why JSON fetch instead of a direct import?
 * The original cultures.ts is 233 KB — importing it bundles ALL province data into every
 * client JS chunk, even when the user only visits one province.
 * Fetching per-province JSON means the browser only downloads what it actually needs.
 */

export interface Culture {
  id: string;
  provinceId: string;
  category: string;
  title: string;
  description?: string;
  youtubeId?: string;
  audio?: string;
  narrator?: string;
  location?: string;
  period?: string;
  image?: string;
  tags?: string[];
  coordinates?: [number, number];
  isLandmark?: boolean;
  video?: string | null;
}

// Simple in-memory cache — avoids re-fetching when the user navigates back
const cache: Record<string, Culture[]> = {};

/** Fetch all cultures for a given province. Results are cached after first fetch. */
export async function fetchCulturesByProvince(provinceId: string): Promise<Culture[]> {
  if (cache[provinceId]) return cache[provinceId];

  try {
    const res = await fetch(`/data/cultures/${provinceId}.json`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data: Culture[] = await res.json();
    cache[provinceId] = data;
    return data;
  } catch (err) {
    console.error(`[fetchCultures] Failed to load cultures for ${provinceId}:`, err);
    return [];
  }
}

/** Fetch a single culture by its ID, looking up the province first. */
export async function fetchCultureById(id: string): Promise<Culture | undefined> {
  // Extract provinceId from the culture ID (e.g. "diy-tari-bedhaya" → "diy")
  // Handles multi-word province IDs like "jawa-tengah", "kalimantan-barat"
  const knownProvinces = ['jawa-tengah', 'kalimantan-barat', 'diy', 'papua'];

  for (const pid of knownProvinces) {
    if (id.startsWith(pid + '-')) {
      const cultures = await fetchCulturesByProvince(pid);
      return cultures.find(c => c.id === id);
    }
  }

  return undefined;
}

/** Fetch province culture counts (lightweight — uses _metadata.json). */
const metadataCache: Record<string, number> | null = null;
let metadataPromise: Promise<Record<string, number>> | null = null;

export async function fetchCultureCount(provinceId: string): Promise<number> {
  if (metadataCache) return metadataCache[provinceId] ?? 0;

  if (!metadataPromise) {
    metadataPromise = fetch('/data/cultures/_metadata.json')
      .then(r => r.json())
      .catch(() => ({}));
  }

  const metadata = await metadataPromise;
  return metadata[provinceId] ?? 0;
}

export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

const quizCache: Record<string, QuizQuestion[]> = {};

export async function fetchQuizByProvince(provinceId: string): Promise<QuizQuestion[]> {
  if (quizCache[provinceId]) return quizCache[provinceId];

  try {
    const res = await fetch(`/data/quizzes/${provinceId}.json`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data: QuizQuestion[] = await res.json();
    quizCache[provinceId] = data;
    return data;
  } catch (err) {
    console.error(`[fetchQuiz] Failed to load quiz for ${provinceId}:`, err);
    return [];
  }
}

